### ISSUE TITLE
Replace copy of VAL in the jenkins directory

### ISSUE THREAD

**Issue by rpgoldman** [shop-planner/shop3#6]
Replace with another git submodule.  Since VAL has bitrotted, it should probably be the patched version that @guicho271828 has.

**Comment by rpgoldman** [comment]
This isn't easy to do, since the state of VAL is still unsettled and its use in SHOP requires the addition of the `-x` command-line option.  Needs further investigation, but the tests are fixed for now at least, as is use of `validate` in SHOP3 functions.

**Comment by guicho271828** [comment]
Is it using any VAL-specific functionality? Otherwise you could consider https://github.com/guicho271828/ArriVAL for validation (only for ADL/PDDL though)

**Comment by guicho271828** [comment]
oops I forgot that it was still missing action costs etc. (please forget about it for now)

**Comment by rpgoldman** [comment]
I am using an extension to `validate` that adds a `-x` argument that will cause `validate` to exit with a non-zero status if the plan fails to validate.

I'm not sure how to get that patch incorporated in the upstream VAL: instead of modifying it slowly, they smashed a huge change in all at once, which makes my patch effectively un-rebase-able. Hence I have to use the old version.

(Editorial complaint: this kind of thing would be a lot easier if validate used getopt instead of a hand-written loop)

**Comment by rpgoldman** [comment]
I would love to incorporate ArriVAL: VAL's parser is ... not nice.  It may have started from a grammar, but by the time the authors were done turning that grammar into something that flex and bison could handle, it was an unreadable mess.
